import type { PrismaClient } from '@prisma/client';

const DEFAULT_PLUGINS = [
  {
    slug: 'ox-lib',
    name: 'ox_lib',
    description:
      'Popular FiveM library for UI, callbacks, locales, and shared utilities. Required by many modern resources.',
    category: 'library' as const,
    tags: ['library', 'standalone', 'esx', 'qb'],
    githubOwner: 'overextended',
    githubRepo: 'ox_lib',
    githubRef: 'latest-release',
    githubAsset: null,
    installPath: '/resources/[ox]/ox_lib',
    cfgResource: 'ox_lib',
    cfgAction: 'ensure',
    cfgFile: '/server.cfg',
    dependencies: [] as string[],
    featured: true,
    sortOrder: 10,
  },
  {
    slug: 'oxmysql',
    name: 'oxmysql',
    description: 'MySQL resource for FiveM. Lightweight database driver used by ESX, QBCore, and ox resources.',
    category: 'library' as const,
    tags: ['library', 'database', 'esx', 'qb'],
    githubOwner: 'overextended',
    githubRepo: 'oxmysql',
    githubRef: 'latest-release',
    githubAsset: null,
    installPath: '/resources/[ox]/oxmysql',
    cfgResource: 'oxmysql',
    cfgAction: 'ensure',
    cfgFile: '/server.cfg',
    dependencies: ['ox-lib'],
    featured: true,
    sortOrder: 20,
  },
  {
    slug: 'pma-voice',
    name: 'pma-voice',
    description: 'Proximity voice chat for FiveM with radio and call channels.',
    category: 'script' as const,
    tags: ['voice', 'standalone'],
    githubOwner: 'AvarianKnight',
    githubRepo: 'pma-voice',
    githubRef: 'latest-release',
    githubAsset: null,
    installPath: '/resources/[voice]/pma-voice',
    cfgResource: 'pma-voice',
    cfgAction: 'ensure',
    cfgFile: '/server.cfg',
    dependencies: [],
    featured: true,
    sortOrder: 30,
  },
  {
    slug: 'ox-inventory',
    name: 'ox_inventory',
    description: 'Slot-based inventory with metadata support. Popular choice for ESX and QBCore servers.',
    category: 'script' as const,
    tags: ['inventory', 'ox', 'esx', 'qb'],
    githubOwner: 'overextended',
    githubRepo: 'ox_inventory',
    githubRef: 'latest-release',
    githubAsset: null,
    installPath: '/resources/[ox]/ox_inventory',
    cfgResource: 'ox_inventory',
    cfgAction: 'ensure',
    cfgFile: '/server.cfg',
    dependencies: ['ox-lib', 'oxmysql'],
    featured: true,
    sortOrder: 40,
  },
  {
    slug: 'ox-target',
    name: 'ox_target',
    description: 'Third-eye targeting system — interact with entities and zones in the world.',
    category: 'script' as const,
    tags: ['target', 'ox', 'standalone'],
    githubOwner: 'overextended',
    githubRepo: 'ox_target',
    githubRef: 'latest-release',
    githubAsset: null,
    installPath: '/resources/[ox]/ox_target',
    cfgResource: 'ox_target',
    cfgAction: 'ensure',
    cfgFile: '/server.cfg',
    dependencies: ['ox-lib'],
    featured: true,
    sortOrder: 50,
  },
];

export async function seedMarketplacePlugins(prisma: PrismaClient) {
  for (const plugin of DEFAULT_PLUGINS) {
    await prisma.marketplacePlugin.upsert({
      where: { slug: plugin.slug },
      update: {
        name: plugin.name,
        description: plugin.description,
        category: plugin.category,
        tags: plugin.tags,
        githubOwner: plugin.githubOwner,
        githubRepo: plugin.githubRepo,
        githubRef: plugin.githubRef,
        installPath: plugin.installPath,
        cfgResource: plugin.cfgResource,
        dependencies: plugin.dependencies,
        featured: plugin.featured,
        sortOrder: plugin.sortOrder,
      },
      create: {
        ...plugin,
        tags: plugin.tags,
        dependencies: plugin.dependencies,
        enabled: true,
      },
    });
  }
}
